### ISSUE TITLE
Cannot install Module on Prestashop v1.7.6.5

### ISSUE THREAD

**Issue by fixmygadgetau** [laybuy/PrestaShop-Module#1]
Having some issues installing laybuy module for prestashop 1.7.6.5 

when selecting the zip for install i get an error message "This file does not seem to be a valid module zip" 
could someone please help with this issue as i need laybuy for my site and dont want to have to move my site to another platform

**Comment by hennaboy** [comment]
Same here. 

> Having some issues installing laybuy module for prestashop 1.7.6.5
> 
> when selecting the zip for install i get an error message "This file does not seem to be a valid module zip"
> could someone please help with this issue as i need laybuy for my site and dont want to have to move my site to another platform

Download the module. Extract it and then go to the directory. 

Create a new directory called laybuy and place everything inside it.

Create a new zip file and then upload this to prestashop and it should install fine

**Comment by fixmygadgetau** [comment]
Thanks for the reply @hennaboy. 
I'll give this a try today and see how it goes
